# -*- coding: utf-8 -*-
"""Submission Time Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L_yRVslRmSwZnzn-rOTKg73UtMw6pR3G

Link Dataset 
https://www.kaggle.com/datasets/meetnagadia/apple-stock-price-from-19802021

https://www.kaggle.com/discussions/getting-started/316278
"""

# install kaggle package
!pip install -q kaggle

# upload kaggle.json
from google.colab import files
files.upload()

# make directory and change permission
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!ls ~/.kaggle

# download dataset, choose 'copy api command' from kaggle dataset
!kaggle datasets download -d meetnagadia/apple-stock-price-from-19802021

from zipfile import ZipFile
file_name = "/content/apple-stock-price-from-19802021.zip"

with ZipFile(file_name,'r') as zip:
  zip.extractall()
  print("done")

import numpy as np
import pandas as pd
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
import tensorflow as tf

data_train = pd.read_csv('/content/AAPL.csv')
data_train.head()

data_train.isnull().sum()

data_train.isnull()

dates = data_train['Date'].values
category  = data_train['Open'].values
 
 
plt.figure(figsize=(15,5))
plt.plot(dates, category)
plt.title('Temperature average',
          fontsize=20);

dates = data_train['Date'].values
category  = data_train['Open'].values

import matplotlib.pyplot as plt

plt.figure(figsize=(20,8))
plt.plot(dates, category)
plt.title('Stock Apple')
plt.xlabel('Dates')
plt.ylabel('category')
plt.show()

def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    series = tf.expand_dims(series, axis=-1)
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size + 1))
    ds = ds.shuffle(shuffle_buffer)
    ds = ds.map(lambda w: (w[:-1], w[-1:]))
    return ds.batch(batch_size).prefetch(1)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(category, dates, test_size = 0.2, random_state = 0 , shuffle=False)
print(len(x_train), len(x_test))

train_set = windowed_dataset(x_train, window_size=60, batch_size=100, shuffle_buffer=1000)
test_set = windowed_dataset(x_test, window_size=60, batch_size=100, shuffle_buffer=5000)

model = tf.keras.models.Sequential([
  tf.keras.layers.LSTM(64, return_sequences=True),
  tf.keras.layers.LSTM(64, return_sequences=True),
  tf.keras.layers.Dense(30, activation="relu"),
  tf.keras.layers.Dense(10, activation="relu"),
  tf.keras.layers.Dense(1),
  tf.keras.layers.Lambda(lambda x: x * 400)
])

optimizer = tf.keras.optimizers.SGD(lr=1.0000e-04, momentum=0.9)
model.compile(loss=tf.keras.losses.Huber(),
              optimizer=optimizer,
              metrics=["mae"])

history = model.fit(train_set,epochs=100,validation_data=test_set)

# plot of mae
import matplotlib.pyplot as plt
plt.plot(history.history['mae'])
plt.plot(history.history['val_mae'])
plt.title('MAE')
plt.ylabel('mae')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

# plot of loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()